"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.bloggersPlatform = void 0;
const express_1 = require("express");
const video_routes_1 = require("./video-routes");
const bloggers_routes_1 = require("./bloggers-routes");
const posts_routes_1 = require("./posts-routes");
const users_routes_1 = require("./users-routes");
const auth_routes_1 = require("./auth-routes");
const comments_routes_1 = require("./comments-routes");
const testing_1 = require("./testing");
exports.bloggersPlatform = (0, express_1.Router)({});
exports.bloggersPlatform.use('/videos', video_routes_1.videoRouter);
exports.bloggersPlatform.use('/bloggers', bloggers_routes_1.bloggersRouter);
exports.bloggersPlatform.use('/posts', posts_routes_1.postsRouter);
exports.bloggersPlatform.use('/users', users_routes_1.usersRouter);
exports.bloggersPlatform.use('/auth', auth_routes_1.authRoutes);
exports.bloggersPlatform.use('/comments', comments_routes_1.commentsRoutes);
exports.bloggersPlatform.use('/testing', testing_1.testing);
